### ISSUE TITLE
WSL2 UDS issue

### ISSUE THREAD

**Issue by vany-egorov** [go-x-pkg/servers#11]
**Environment:** Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux

**Config:**
 ```
- kind: [unix, http]
    addr: /tmp/test.sock
```

**Expected result:**
Run server on UNIX domain socket;

**Happened:**
```error: listen unix (/tmp/test.sock) server failed: listen unix /tmp/test.sock: bind: A socket operation encountered a dead network.```

**Comment by r-novel** [comment]
Have created ticket into Go repo:
https://github.com/golang/go/issues/44797

**Comment by r-novel** [comment]
Yes! I've understood what happened.

**tl;dr** don't run the application from mounted Windows FS (`/mnt/c/Users/bla-bla-bla`) using WSL.

I've moved source code to WSL `/home` and the application has started and worked correctly.
Closed.

**Comment by vany-egorov** [comment]
@r-novel OK. Thanks!
